--- #YAML:1.0
name:               Math-NumSeq
version:            21
abstract:           Number sequences.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    constant:           1.02
    constant::defer:    1
    File::HomeDir:      0
    File::Spec:         0
    File::Temp:         0
    List::Util:         0
    Math::Libm:         0
    Math::Prime::XS:    0.23
    Module::Load:       0
    Module::Pluggable:  0
    Module::Util:       0
    perl:               5.004
    Test:               0
resources:
    homepage:  http://user42.tuxfamily.org/math-numseq/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - xt
        - devel
        - examples
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            B::Concise:           0
            Bit::Vector:          0
            Devel::Comments:      0
            Devel::TimeThis:      1
            File::Spec:           0
            Math::BigRat:         0
            Math::Fibonacci:      0
            Math::Polynomial:     1
            Math::Prime::TiedArray:  1
            Math::TriangularNumbers:  1
            Parse::CPAN::Meta:    0
            Path::Class:          0
            Pod::Simple::HTML:    0
            Smart::Comments:      0
            String::BitCount:     0
            String::Parity:       0
            Test::DistManifest:   0
            Test::Pod:            1.00
            Test::Synopsis:       0
            Test::YAML::Meta:     0.15
            warnings::unused:     0
            YAML:                 0
            YAML::Syck:           0
            YAML::Tiny:           0
            YAML::XS:             0
    maximum_interoperation:
        description:  Have maximum inter-operation with other modules (optional other stuff).
        requires:
            Language::Expr:       0
            Language::Expr::Compiler::Perl:  0
            Math::Expression::Evaluator:  0
            Math::Symbolic:       0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            Data::Float:  0
recommends:
    Math::Prime::XS:  0.26
